### ISSUE TITLE
add more interactive components, part 1

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#1]
- [x] images from url
 - [ ] upload images + drag and drop
 - [ ] image captions
 - [x] charts
 - [x] iframes
 - [x] maps
 - [x] <strike> soundcloud </strike> available from embeds
 - [x] videos
 - [x] custom (for youtube embeds, etc)

**Comment by PalmerAL** [comment]
these should use web components

**Comment by PalmerAL** [comment]
@nt1m what do you think a good icon for the custom embeds would be?

**Comment by nt1m** [comment]
@PalmerAL Maybe an <> icon

**Comment by nt1m** [comment]
It'd be nice to have a text area component (probably using the rich cards)

**Comment by nt1m** [comment]
A symbols component would be nice as well (probably using the icon font).
