### ISSUE TITLE
renaming scratchpad

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#102]
There are <a href="https://duckduckgo.com/?q=scratchpad"> about a billion other things </a> named scratchpad, so I think a different name is required.

(@haze007 I like docolate as a name but there is already <a href="https://github.com/MandarinConLaBarba/docolate">something else using that name</a>)

**Comment by nt1m** [comment]
How about Scriber

**Comment by haze007** [comment]
Oh wow! That's nice

**Comment by PalmerAL** [comment]
Doccan? (Document + canvas)

**Comment by nt1m** [comment]
@PalmerAL Not a big fan of Doccan, sounds like Duncan. The "can" part is also misleading, people can think it's a way to store your docs (in a can ;) )
How about PaperScratch ? Paper as in Material Design and as in writing. Scratch as in writing/scratching on paper.

**Comment by PalmerAL** [comment]
I don't know about the "scratch" part - hard to understand without the explanation.

**Comment by PalmerAL** [comment]
Krei?  ("Create" in Esperanto)

**Comment by PalmerAL** [comment]
Scrivjen? (Loosely based on "schrijven", which is "write" in Dutch.

**Comment by nt1m** [comment]
@PalmerAL Your suggestions are hard to guess too. What you could do though is experiment with the english synonyms of "write" (scratch is one of them)

**Comment by PalmerAL** [comment]
slatescribe?

**Comment by PalmerAL** [comment]
Basically, someone is already using every possible easy-to-understand name. Something that sounds good will probably have to be good enough.

**Comment by nt1m** [comment]
@PalmerAL Slatescribe doesn't illustrate what the editor is about. The editor is about simple, fast,  minimal editing. Slate is "a rock", and writing on rock is the opposite of simple and fast.

**Comment by nt1m** [comment]
Also, slate is already a magazine, so people can think the editor is related to it.

**Comment by PalmerAL** [comment]
Scrivere?

**Comment by PalmerAL** [comment]
It's probably time to decide on a name. So far, I'm leaning towards krei, but I could also see using a different name.

**Comment by nt1m** [comment]
I vote for PaperScribe/PaperScratch

**Comment by PalmerAL** [comment]
http://www.paperscribe.com/ already exists, but it appears to not be a real business (lots of "lorem ipsum", none of the links work, etc..)

Maybe DocLayer? (based on the idea of material design having different layers).

**Comment by nt1m** [comment]
DocLayer seems nice.

**Comment by PalmerAL** [comment]
If you think that's good, I'm probably going to go with that. https://github.com/jitix/doclayer is the only thing I can find already using that name, and it isn't at all related, nor is it well known. In addition, getdoclayer.com and doclayerapp.com are both still available (if I buy a domain name, I think I'll try and get some feedback on the editor first).

**Comment by PalmerAL** [comment]
#210
