### ISSUE TITLE
Support copy pasting from Google Docs/word

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#109]

**Comment by PalmerAL** [comment]
I'm not sure this is really possible. Word at least gives normal formatting tags, so you would just have to strip out its custom styles. The google docs data, though, is just a bunch of span's with style attributes. I'm not sure it's really possible to convert those into formatting tags.

**Comment by PalmerAL** [comment]
Some basic support for this is in 26fe7656b1b45c4078393943506b3164da2c411e. It could probably be better, though.
