### ISSUE TITLE
faster find and replace

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#11]
when the find and replace is used on a longer document (>5000 characters), the page freezes when find in page is used.

**Comment by PalmerAL** [comment]
this is firefox-specific. tracking at https://bugzilla.mozilla.org/show_bug.cgi?id=1126635

**Comment by PalmerAL** [comment]
@nt1m this is because of the contenteditable attribute. Would it be a good idea to turn contenteditable off while searching in page until this is fixed?

**Comment by nt1m** [comment]
Yeah, probably.

**Comment by PalmerAL** [comment]
Okay, I switched this to turning off contenteditable when searching. Hopefully, this bug will be fixed soon and this can be removed.
