### ISSUE TITLE
Scratchpad doesn't work on Opera

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#110]
No console logs

**Comment by PalmerAL** [comment]
Scratchpad only supports Chrome, Safari, mobile Safari, and Firefox. Depending on the source, Opera has between a 1-3% market share. I don't think its worth it.

**Comment by nt1m** [comment]
No, I mean Webkit Opera (so chrome must be affected as well)

**Comment by PalmerAL** [comment]
Oddly, this works in Chrome.
