### ISSUE TITLE
Header is sometimes white on dark theme

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#113]
I can't reproduce often.

**Comment by PalmerAL** [comment]
Which header?

**Comment by nt1m** [comment]
Editor header

**Comment by PalmerAL** [comment]
I guess I'll go ahead and close this for now, since there aren't steps to reproduce. This sounds a lot like a browser bug - the darktheme just adds and removes a class from the body, so the results should be the same every time.
