### ISSUE TITLE
better spellchecker ux

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#135]
there are a few issues with the current spellchecker ux:
 - you can't click to move the cursor, as it autocorrects the word instead
 - the context menu is hard to discover
 - its unclear why words are colored pink

@nt1m ideas?

**Comment by nt1m** [comment]
I would just go with a normal spellcheck ui here, with the red dotted underline for incorrect words. It should be pretty obvious that way that there is a context menu
