### ISSUE TITLE
Use a Google inbox like add menu

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#14]
I think having a menu with a bunch of small fabs popping out like in Google inbox would be cool, instead of a menu.

**Comment by PalmerAL** [comment]
I don't have access to Google inbox. Can you post a photo of what you are thinking of?

**Comment by nt1m** [comment]
I invited you to inbox, you can click the red fab, and youll see some small fabs sliding out as well

**Comment by PalmerAL** [comment]
Okay, I updated the menu to use fabs for the items. It still needs different colors for the items, labels, and probably a better animation.

**Comment by nt1m** [comment]
@PalmerAL Yep, Google inbox uses has a slide out effect from the big fab when hovering.
Tooltips would be nice as well, since some icons are ambigous (the 2 write icons, and the divider one).
For the 2 write icons, I would suggest you just put h1 and h2 as fab labels.
