### ISSUE TITLE
fix licensing

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#157]
There is some apache 2.0-licensed software (material-framework and mousetrap) that are dependencies, and I just learned these aren't compatible with gpl 2. Mousetrap has an alternative, jquery.hotkeys, but I'm not sure what to do about material-framework. I could upgrade to gpl 3, or material-framework could change licenses. @nt1m which one do you think?

**Comment by PalmerAL** [comment]
The other option is to not license scratchpad under gpl, and instead use mit, mozilla, or similar. This might be a better option, as it avoids most of these issues.

**Comment by nt1m** [comment]
@PalmerAL I will probably switch my repos to an MIT license. I don't even remember how I ended up choosing Apache. Anyway, I recommend you to use another license (or upgrade gpl to v3), so you can use the dependencies you need.

**Comment by PalmerAL** [comment]
I'll probably switch to a different license, as I can't change the license on mousetrap. Also, GPL is incompatible with a lot of licenses anyway, and I'm not sure what other dependencies will be needed in the future.

**Comment by PalmerAL** [comment]
I switched to MPL license, which is hopefully compatible with all dependencies - as far as I can tell, it works fine with all current dependencies, and hopefully will work in the future.
