### ISSUE TITLE
image delete button doesn't always appear

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#159]
I reproduced this by injecting the research sidebar images and then hovering them in the doc

**Comment by PalmerAL** [comment]
Actually, its broken on everything.

**Comment by PalmerAL** [comment]
Fixed. The version of editor.js on standaert.net had a typo in it from 6ff703a9159790cadea898f2a61984620a878db6 that I fixed before pushing and then forgot to re-upload.

**Comment by PalmerAL** [comment]
(you may need to force-reload https://standaert.net/scratchpad/editor/js/editor.js)
