### ISSUE TITLE
Improve simple url dialogs UX

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#167]
I feel like the dialogs with only an url input can have their UX improved. Here are some suggestions :
- Increase the width of the inputs
Makes sense, since urls are long. Probably the same width as the input in the maps dialog is enough
- Improve title
So the spec mentions that titles should only be used for high risk actions, but in this case, the dialog would just look weird without one
- Add a preview
Maybe a simple preview for what the user is going to insert would be great

**Comment by PalmerAL** [comment]
- Width was fixed.
 - Preview can wait for 1.1 (filed #198 about this).

What improvements should be made to the titles?
