### ISSUE TITLE
Dropbox integration is broken

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#169]
When I sign in, the site makes me go back and forth from the homescreen to the doclist

**Comment by PalmerAL** [comment]
Probably, you want to force-reload https://standaert.net/scratchpad/doclist/doclist.js.

The whole caching issue is something I haven't really figured out yet, but this probably needs to get fixed before 1.0.

**Comment by PalmerAL** [comment]
Closing for now. Reopen if this happens again.
