### ISSUE TITLE
Sidepanel slide animation

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#183]

**Comment by PalmerAL** [comment]
What do you think of something like this?

```
.sidebar[hidden] {
	display: block;
	height: 0;
	top: 40px;
}

.sidebar {
	width: 50%;
	min-width: 320px;
	max-width: 550px;
	height: calc(100% - 65px);
	overflow: auto;
	position: fixed;
	right: 0;
	top: 65px;
	z-index: 99;
	transition: 0.15s ease;
	box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.26), 0 2px 10px 0 rgba(0, 0, 0, 0.16);
}
```

**Comment by nt1m** [comment]
I think a slide animation from the side (similar to the sidemenu one, but from the right) makes more sense here. I haven't seen much animations like this in MD apps so far.

**Comment by PalmerAL** [comment]
Something like this then?

```
.sidebar[hidden] {
    display: block;
    rght: -550px;
}

.sidebar {
    width: 50%;
    min-width: 320px;
    max-width: 550px;
    height: calc(100% - 65px);
    overflow: auto;
    position: fixed;
    right: 0;
    top: 65px;
    z-index: 99;
    transition: 0.2s ease;
    box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.26), 0 2px 10px 0 rgba(0, 0, 0, 0.16);
}
```

**Comment by nt1m** [comment]
Looks good :+1: ! Tweaked a bit the CSS so the box-shadow isn't visible when the sidebar is hidden.
<code>
.sidebar[hidden] {
    display: block;
    right: -550px;
    box-shadow: none;
}

.sidebar {
    width: 50%;
    min-width: 320px;
    max-width: 550px;
    height: calc(100% - 65px);
    overflow: auto;
    position: fixed;
    right: 0;
    top: 65px;
    z-index: 99;
    transition: right 0.2s ease;
    box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.26), 0 2px 10px 0 rgba(0, 0, 0, 0.16);
}
</code>

**Comment by PalmerAL** [comment]
Fixed in 295c9802c3f8f15e5ffdac650588e45c63191ff0.

I changed the css to ```right: 575px``` instead of hiding the box shadow. Hiding the box shadow causes performance issues since the shadow is animated as well.

**Comment by nt1m** [comment]
@PalmerAL The shadow isn't animated, the transition property only animates the right property in the code I wrote

**Comment by PalmerAL** [comment]
Oh, I didn't notice that.
