### ISSUE TITLE
Perf improvements

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#20]
Here are some improvements I suggest : 
- Put the jquery script *just* before all the other scripts (so the page can rendering without waiting for all scripts to load)
- Use Google's CDN, the CDN you used is really slow on my network

**Comment by PalmerAL** [comment]
Thanks! I moved jquery to the bottom. I'm not sure about using the google cdn. Using webpagetest, the google cdn takes more than twice as long as the cloudflare one (535 ms vs 238 ms).
