### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#26]
- [x] Icon
- [x] Accent color
- [x] Header border is too dark
- [x] More padding around content (50px looks good to me)
- [x] cleaner demo

**Comment by PalmerAL** [comment]
I would add to this coming up with a better name.

**Comment by PalmerAL** [comment]
Some early ideas for a logo.
![screen shot 2015-01-29 at 5 09 54 pm](https://cloud.githubusercontent.com/assets/10314059/5968168/45bc4cee-a7da-11e4-8c00-ae013454b479.png)
![screen shot 2015-01-29 at 5 10 39 pm](https://cloud.githubusercontent.com/assets/10314059/5968170/45c14b36-a7da-11e4-9d60-690441423eae.png)
![screen shot 2015-01-29 at 5 13 53 pm](https://cloud.githubusercontent.com/assets/10314059/5968169/45bef1d8-a7da-11e4-95ae-3c799a0b18e0.png)

**Comment by PalmerAL** [comment]
I updated the padding. It now is a minimum of 25px and scales up as the screen size increases.

**Comment by nt1m** [comment]
You could ask Michael Cook on Google+, he makes great icons.

**Comment by nt1m** [comment]
I think the divider demo should be removed (or be more naturally integrated). Also, I would capitalize the headings properly.

**Comment by nt1m** [comment]
![scratchpad](https://cloud.githubusercontent.com/assets/1795135/6201504/a03bbf3e-b4ae-11e4-90a1-38910fca2490.png)
How do you like this ? It's not perfect yet (the bent corner needs to be round).

**Comment by PalmerAL** [comment]
Nice, but it looks really similar to the Google Docs logo. I think we need something that makes it clear that this is not google docs.

**Comment by PalmerAL** [comment]
Maybe switching the text bars to a pencil icon or adding some image + map + chart icons or something

**Comment by PalmerAL** [comment]
![screen shot 2015-02-14 at 6 28 13 pm](https://cloud.githubusercontent.com/assets/10314059/6201565/52d4b016-b477-11e4-8d59-0c1933048e64.png)

**Comment by PalmerAL** [comment]
some more ideas:
![screen shot 2015-02-15 at 9 57 35 am](https://cloud.githubusercontent.com/assets/10314059/6203796/1c526fd8-b4f9-11e4-8df4-d8c0d6f68723.png)
![screen shot 2015-02-15 at 9 54 18 am](https://cloud.githubusercontent.com/assets/10314059/6203795/1c520e80-b4f9-11e4-947f-a1c24d270d49.png)
![screen shot 2015-02-15 at 9 53 17 am](https://cloud.githubusercontent.com/assets/10314059/6203798/1c554ea6-b4f9-11e4-9a0f-df346b5b91fa.png)
![screen shot 2015-02-15 at 9 50 54 am](https://cloud.githubusercontent.com/assets/10314059/6203797/1c53b834-b4f9-11e4-9b36-8ccc48ef1d41.png)
![screen shot 2015-02-15 at 9 50 10 am](https://cloud.githubusercontent.com/assets/10314059/6203799/1c5695ea-b4f9-11e4-892b-33f4d46d2adb.png)

**Comment by PalmerAL** [comment]
some more ideas: 
![screen shot 2015-02-20 at 5 12 12 pm](https://cloud.githubusercontent.com/assets/10314059/6311119/cd421446-b923-11e4-9f2f-97dbe8ba413f.png)
![screen shot 2015-02-20 at 5 12 35 pm](https://cloud.githubusercontent.com/assets/10314059/6311121/cd4bce1e-b923-11e4-9aaf-c964e3b770e7.png)
![screen shot 2015-02-20 at 5 13 08 pm](https://cloud.githubusercontent.com/assets/10314059/6311120/cd4a3950-b923-11e4-9ab0-e5c549fc4d16.png)

I think its probably time to choose a logo for this. @nt1m Which one do you think is the best (or is there something else you like better)?

**Comment by nt1m** [comment]
@PalmerAL I like the book icon better, but the color isn't right for me. Maybe teal-500 could be nice. Also, only flat shadows should be used in icons. No drop-shadows.

**Comment by PalmerAL** [comment]
Book icon set in teal 500 and blue 600:

![screen shot 2015-02-21 at 10 17 37 am](https://cloud.githubusercontent.com/assets/10314059/6314809/f59c3f54-b9b2-11e4-8128-d29f9ae840a0.png)
![screen shot 2015-02-21 at 10 17 31 am](https://cloud.githubusercontent.com/assets/10314059/6314810/f59d379c-b9b2-11e4-9b07-5d5832e7bd0a.png)

**Comment by PalmerAL** [comment]
It could be without the border box also: 
![screen shot 2015-02-21 at 10 21 27 am](https://cloud.githubusercontent.com/assets/10314059/6314828/715d6a8c-b9b3-11e4-993f-9f167fec1880.png)

**Comment by nt1m** [comment]
I like this version best : https://cloud.githubusercontent.com/assets/10314059/6314810/f59d379c-b9b2-11e4-9b07-5d5832e7bd0a.png
Can you try with a folded corner on top right ?

**Comment by PalmerAL** [comment]
Sure! Some different sizes of a corner:

![screen shot 2015-02-21 at 11 46 32 am](https://cloud.githubusercontent.com/assets/10314059/6315178/5349b904-b9bf-11e4-96a0-577e811084e8.png)
![screen shot 2015-02-21 at 11 46 19 am](https://cloud.githubusercontent.com/assets/10314059/6315179/534ae1f8-b9bf-11e4-8885-8c034e968549.png)
![screen shot 2015-02-21 at 11 45 52 am](https://cloud.githubusercontent.com/assets/10314059/6315177/53481946-b9bf-11e4-92a0-439e3eba344a.png)

**Comment by PalmerAL** [comment]
Or with a corner darker than the main box:

![screen shot 2015-02-21 at 11 47 46 am](https://cloud.githubusercontent.com/assets/10314059/6315183/7d8ea1fc-b9bf-11e4-9652-968260d923a3.png)

**Comment by nt1m** [comment]
It definitively looks nicer, now if you can move down a bit the white icon and round the fold corner, I think it would look perfect :)
Well, the fold corner should be lighter, but a darker flat shadow should appear beneath it (see the Docs logo).

**Comment by PalmerAL** [comment]
![screen shot 2015-02-21 at 12 03 02 pm](https://cloud.githubusercontent.com/assets/10314059/6315242/a163ffda-b9c1-11e4-80b0-243cb7f1f1ec.png)

I'm not quite understanding what you mean by "round the fold corner". Should the edges of the fold be round?

**Comment by nt1m** [comment]
@PalmerAL If you take a look at the Google Docs icon, the square edge of the folded corner is round.

**Comment by nt1m** [comment]
Btw, can you center the white icon horizontally and move it down a bit ?

**Comment by PalmerAL** [comment]
![screen shot 2015-02-21 at 12 51 34 pm](https://cloud.githubusercontent.com/assets/10314059/6315463/660bfbac-b9c8-11e4-85f4-1d5cac019d02.png)

**Comment by nt1m** [comment]
Looks perfect to me :+1:

**Comment by PalmerAL** [comment]
What's the best way to render this? Right now it is drawn using <a href="http://jsfiddle.net/s7j74vjL/8/">this jsfiddle</a>, but it could be rendered using an svg or regular image as well.

**Comment by PalmerAL** [comment]
And would the accent color be the same teal color?

**Comment by nt1m** [comment]
@PalmerAL I created an app that can render HTML on a PNG file. It's not live yet, but I can use it for your logo. But the best solution here is to create an SVG, I can take care of it, but probably not this week.

**Comment by nt1m** [comment]
As for the accent color, no, the logo color is the navigation color (the toolbar color). The accent color is usually a color that is complementary with that navigation color (pink seems like a good candidate, but it's really up to you to choose here).

**Comment by PalmerAL** [comment]
Okay. For now, this can just be rendered in HTML.

**Comment by nt1m** [comment]
Btw, in MD, the accent color is usually used as main toolbar color.
Here's a site that demos well how colors should be used : http://www.materialpalette.com/teal/pink

**Comment by PalmerAL** [comment]
I tried that, but it gets very distracting. Also, I think that there is <a href="https://medium.com/@abrodo/an-exploration-in-material-design-by-feedly-8c1a1cbdfdcd">some room for interpretation</a>on this.

**Comment by nt1m** [comment]
@PalmerAL i do think it looks a bit boring without color, but that's a matter of taste.

**Comment by haze007** [comment]
I've two off-topic suggestions besides my TogetherJS suggestion:
* What about renaming the project as 'Docoloate' instead of Scratchpad since a Chrome app already exists with that name? Docolate is a mixture of Chocolate and Documents since material UI is inspired for Android Lollpop and both of them are sweets.

*I think keeping the color of the toolbar where you enter the document name and stuff like that, as blue instead of plain white which looks 'okay'. The menu button on the toolbar doesn't work or it appears to be a dummy button. Maybe the collaborate button can take it's place if that's not meant to be there.

**Comment by PalmerAL** [comment]
@haze007 the menu button is supposed to take you back to the documents list or show you frequently edited documents - see an example <a href="https://Standaert.net/scratchpad"> here </a>.

**Comment by PalmerAL** [comment]
@nt1m while it is boring  it also isn't distracting like a color is. Maybe a color that fades out as you scroll down would work.

**Comment by nt1m** [comment]
@PalmerAL I don't find colored header particularly distracting, it's just a matter of habit I think.
Anyway, if you choose to keep the header non-colored, I would suggest to make the header border lighter (rgba(0, 0, 0, 0.12)) and make the background light gray (#F4F4F4 maybe ?), kinda like the feedly design.

**Comment by haze007** [comment]
Ah are you going to upload the code with the Dropbox integration? preferably with some documentation regarding that part would be more helpful. Can't wait to see this project grow.

**Comment by PalmerAL** [comment]
@haze007 code's way too buggy too merge now. Will add as soon as most of the major issues are fixed (if you find issues, add them to #75 )

**Comment by PalmerAL** [comment]
@haze007 I have added the dropbox code now. You will need to register for an app key and replace DROPBOX_APP_KEY in the project with your app key before you can run it.
