### ISSUE TITLE
Delete block button issues

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#35]
- [x] Shows on top of dialogs
- [ ] Should disappear when scrolling

**Comment by PalmerAL** [comment]
Now that it moves with the page, I'm not sure it needs to disappear.

**Comment by nt1m** [comment]
@PalmerAL , that's fine to me, can you do the same for the research add button ?

**Comment by PalmerAL** [comment]
The problem is that the thing the button appears for is in something that scrolls separate from the body. This would need something to calculate the image offset relative to the panel so the button can scroll inside the panel.

**Comment by PalmerAL** [comment]
Fixed the research button.
