### ISSUE TITLE
Typography improvements

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#36]
- [x] h1 font is too light (update material-framework to fix that)
- [x] h2's border is too dark (make it match the dividers)
- [x] Allow setting h2 without border
- [x] Allow to specify alignment
- [x] Match MD spec for font-size : http://www.google.com/design/spec/style/typography.html#typography-standard-styles

**Comment by PalmerAL** [comment]
The only thing really blocking adding alignment is the lack of an icon in the icon font. Maybe just use regular svg or have a second font?

**Comment by nt1m** [comment]
It's better to use a regular svg here : google/material-design-icons
Or... You could extend the current font using fontello, then contribute back the changes ;)
