### ISSUE TITLE
Be consistent with indenting

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#40]
Right now, indenting is a mix of tab indenting and 2 spaces indenting. I'd be nice to be consistent.

Tips for choosing : 
- Tabs take less file size and can be configured
- 2 spaces are more used (I don't understand why though)

**Comment by PalmerAL** [comment]
Apparently, spaces are used because they are consistent across text editors (while tabs aren't). I don't really have a preference on this though - whatever you think is fine.

**Comment by nt1m** [comment]
@PalmerAL I usually use tabs since they save file size. But I don't have a deep preference.
