### ISSUE TITLE
Research sidebar issues

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#43]
- [ ] the design is kind of ugly and involves a lot of duplicate css
 - [ ] sometimes, the api throws an error and the sidebar is just blank (nt1m/infocards.js#7)
 - [ ] the navbar/header combo wastes a lot of space
 - [x] some images (such as app icons) look really pixelated because they are scaled up from 16x16
 - [x] image search (from google images api)
 - [ ] definitions (wordnik api)

**Comment by nt1m** [comment]
I'd probably use cards as a start. But this needs more options into the infocards library (to avoid having duplicate CSS).

**Comment by nt1m** [comment]
Also, the fact that the searchbox has 2 different functionalities is confusing.
It also makes the research sidebar undiscoverable. 
I'd probably add a separate button for the research sidebar (dictionary icon ?).
