### ISSUE TITLE
Research sidebar bug

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#44]
If you type really fast, the research sidebar sometimes shows the content twice. I think that the html is removed in the second keypress before the first keypress has time to get an api response and create its infocard.

**Comment by nt1m** [comment]
That seems a bug in the library in general, I never really got the time to find the root issue though.

**Comment by nt1m** [comment]
Might be related to https://github.com/nt1m/InfoCards.js/issues/1
