### ISSUE TITLE
Scratchpad keeps saying I'm offline

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#48]
I see requests for favicon.ico every time I click "Reconnect"

**Comment by PalmerAL** [comment]
This happens whenever you try to use scratchpad as a local file and not on a server. Not really sure why this is happening.

**Comment by PalmerAL** [comment]
Also, adding a favicon file doesn't work.

**Comment by nt1m** [comment]
@PalmerAL It happens simply by visiting http://palmeral.github.io/scratchpad/

**Comment by PalmerAL** [comment]
Interesting. I'm not seeing that.

**Comment by PalmerAL** [comment]
This is no longer relevant now that offline has been removed.
