### ISSUE TITLE
Keyboard shortcuts don't work well

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#57]
I'm using a french keyboard, but I'm not sure if it's the root reason here, but it's good to know.

When I do Ctrl+U it invites me to create a link, and all other combinations will focus the searchbox.

Escape and Ctrl+F work well though.

**Comment by PalmerAL** [comment]
Seems fine to me in firefox and safari. Most do nothing in chrome for some reason - will need to look into this. I don't have a french keyboard to test with, so if you have any ideas about how to fix this, let me know.

**Comment by nt1m** [comment]
@PalmerAL Chrome probably forbids some combinations since they might be used for their own shortcuts.

**Comment by nt1m** [comment]
@PalmerAL Now doing Ctrl+(anything) will open the research pane, focus the searchbox and invite me to create a link.

**Comment by PalmerAL** [comment]
Just wondering, do the examples at http://craig.is/killing/mice work correctly?

**Comment by nt1m** [comment]
@PalmerAL Works fine, except for the shortcuts used by the browser.

**Comment by PalmerAL** [comment]
Okay, I'll probably switch to that. That will allow for three or more keys
in a shortcut anyway.

**Comment by PalmerAL** [comment]
@nt1m I've updated to using mousetrap, so these should work now.

**Comment by PalmerAL** [comment]
@nt1m do the shortcuts work now?

**Comment by nt1m** [comment]
@PalmerAL They do, #68 is still reproducible though
