### ISSUE TITLE
Update InfoCards library

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#58]
The latest version has all the options you need to : 
- execute a function when a heading is clicked
- add class names to some parts of the card DOM
- add error callbacks
- add horizontal scrolling (but you're not affected by this)
As a plus, it also now has support for color codes, categories and most exclusive answers.

**Comment by nt1m** [comment]
Also forgot, it now automatically adds a ddg link and adds support for appReferName (&t=scratchpad).

**Comment by PalmerAL** [comment]
Okay, will update when I get time (probably tomorrow)
