### ISSUE TITLE
faster loading

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#60]
As the number of modules has grown the pageload times have gotten substantially slower. Basically, I'm thinking there should be three types of modules:
 - api (like keyboard shortcuts) that are loaded immediately
 - feature (like editortooltip) that are loaded next
 - addon (basically everything in the insert menu) that are loaded after a delay of 5-7 seconds so they don't slow down the rest of the page

@nt1m suggestions?

**Comment by nt1m** [comment]
@PalmerAL You could load modules when needed, for example the research module could be loaded when the research button is clicked, same for find in page. That would require some changes in the code though.

**Comment by PalmerAL** [comment]
Possibly, but this will seem more responsive if the module is already loaded when the button is clicked.

**Comment by PalmerAL** [comment]
switched to two tiers of modules + async (almost everything)

before: http://www.webpagetest.org/video/compare.php?tests=150218_KE_81b2490b551649141c021c753a790d02-r:1-c:0

after : http://www.webpagetest.org/video/compare.php?tests=150218_DT_6ef46922e9ad4c8b05de90b2984d99c7-r:1-c:0
