### ISSUE TITLE
iOS compatibility

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#61]
- [x] position sticky acts really weird
 - [x] crashes on ios7 if you attempt to start typing before editortooltip is done loading
 - [x] header looks weird with dialogs
 - [x] <strike>insert menu is hidden by keyboard</strike> this isn't really fixable
 - [x] <strike>embeds are wrong height</strike> known safari bug, only fix is to add a bunch of ugly markup
 - [x] <strike>dialog buttons must be pressed twice to close</strike> fixed in material-framework

**Comment by nt1m** [comment]
The editor tooltip doesn't seem to work for me (I use iOS 8).

**Comment by PalmerAL** [comment]
I know. Unfortunately, it appears that iOS doesn't support custom tooltips for this. If you find a workaround for this, let me know!

**Comment by PalmerAL** [comment]
Well... about half of these have been fixed, but the big issues are mostly unfixable. not sure what to do about this.

**Comment by PalmerAL** [comment]
Actually, it turns out that you can have some kind of custom editor tooltip. You can't hide the default one, though, so now there are two tooltips.
