### ISSUE TITLE
charts improvements

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#63]
- [x] more chart types
 - [x] cleaner dialog
 - [x] edit charts after they are created
 - [x] dark theme support

**Comment by PalmerAL** [comment]
@nt1m do you think the text for the fields in the table editor should be center aligned or aligned to the right?

**Comment by nt1m** [comment]
@PalmerAL I'm fine with left :)

**Comment by PalmerAL** [comment]
Oh, sorry, that was supposed to say left instead of right!
