### ISSUE TITLE
Charts are buggy

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#66]
They don't seem to work properly for me. It just renders a frame with the data table, and sometimes it doesn't render anything at all.

**Comment by nt1m** [comment]
One other thing, it feels a bit weird having charts in orange (at least to me), maybe you can put maps in red and charts in green.

**Comment by PalmerAL** [comment]
Sometimes, the factmint js is returning a 500 server error or the js, causing the chart to not render. Not sure why this happens - guess I should email them and ask.

**Comment by nt1m** [comment]
@PalmerAL You can simply host their script here right ?

**Comment by PalmerAL** [comment]
I think not - factmint isn't open-source. (at some point, I should just write a table-to-chart converter that is)

**Comment by PalmerAL** [comment]
Actually, what's happening here is that (since allow-same-origin was removed from the iframe), the chart is loading from a unique origin. since you have to register your domain with factmint, the script is not loading.

**Comment by PalmerAL** [comment]
I added back the same-origin for now. Hopefully at some point there will be a way to add real sandboxing to this in a way that will work.

**Comment by PalmerAL** [comment]
Now it's not working at all. I'm thinking that <a href="https://github.com/filamentgroup/jQuery-Visualize"> this </a> might be better (and its open-source), but it doesn't offer as many chart types.

**Comment by PalmerAL** [comment]
btw, the chart issues only occur in firefox. I have contacted factmint - hopefully they will have a solution for this.

**Comment by nt1m** [comment]
You could try ditching srcdoc. And use src="data:text/html,...." instead.

**Comment by PalmerAL** [comment]
Okay, factmint has fixed this - it works now.
