### ISSUE TITLE
Rely on a different API for image search

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#69]
The google API was planned to be shut down in October 2014 or something like that, and it was deprecated in 2010. So maybe SC should rely on another API, since it can be shut down at any time.

**Comment by PalmerAL** [comment]
There doesn't seem to really be a good free api for this. Wikimedia commons looks interesting, but it would require jsonp, which doesn't seem like a good idea.

**Comment by nt1m** [comment]
@PalmerAL I don't see anything wrong with JSONP, InfoCards relies on JSONP FYI.

**Comment by PalmerAL** [comment]
Oh, I thought wikimedia didn't support https, but apparently they do. This should work then.
