### ISSUE TITLE
question about module loading

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#71]
@nt1m So I was trying to stop using jquery in this since the file size is kind of huge, however I've run into a problem.

For some reason, when jquery is removed, the modules do not load. I have removed all the jquery functions from the module loader, there are no errors, and the firefox devtools show the script tags as being in the dom. However, none of the scripts actually run (even adding something like alert("loaded") to the beginning of a module file does not work).

Code for the module loader at https://gist.github.com/PalmerAL/56ef58eac0b5f88b54e0 (I've replaced the $ and append functions with an equivalent)

**Comment by nt1m** [comment]
You removed $(function() { }); around scratchpad.init().
That corresponds to : 
window.addEventListener("DOMContentLoaded", scratchpad.init);

That might not be the root cause though (but I still recommend including it).
I don't see anything wrong in your code otherwise (except the $ functions). Can you publish your code without the $ functions ?

**Comment by nt1m** [comment]
Also, that might also be because of a syntax error in the modules.

**Comment by PalmerAL** [comment]
I think not, though, because (1) there are no errors in the console and (2) the alert() should still run. I'll try the DOMContentLoaded though.

**Comment by PalmerAL** [comment]
Also, if you add it as a regular script tag to the html, it loads.

**Comment by nt1m** [comment]
Maybe it's because of async, I remeber having issues locally with async on chrome once. Putting things on a server fixed things

**Comment by PalmerAL** [comment]
Thinking about this more, I'm not sure its even feasible to get rid of jquery. In particular, I would like to add <a href="https://github.com/mathquill/mathquill">mathquill</a> at some point, and that requires jquery.
