### ISSUE TITLE
Starring paragraphs doesn't work

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#72]
I use Firefox

**Comment by PalmerAL** [comment]
This is because firefox just adds br tags instead of actually creating paragraphs. What do you think the solution to this is?

**Comment by PalmerAL** [comment]
I switched this to allowing anything to be starred. this doesn't help in most cases, though, because the text is usually not wrapped in any tag.

**Comment by nt1m** [comment]
@PalmerAL I should have clarified, it does show the star, but clicking on it doesnt do anything

**Comment by nt1m** [comment]
Maybe that's just for newly created p

**Comment by PalmerAL** [comment]
Hmmm... This should work correctly. Is there anything in the console?

**Comment by nt1m** [comment]
That's the scary part, no. But things might have changed though, but i wont have time to test (at least not today)

**Comment by PalmerAL** [comment]
Also, headings have an issue where clicking the very right edge of the star doesn't work.

**Comment by PalmerAL** [comment]
Closing for now as WFM. If you can reproduce again, please reopen.
