### ISSUE TITLE
dropbox integration tasks

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#75]
a list of things still to do on the dropbox integration

 - [x] cleanup the doclist ui
 - [x] make sure changes at the same time are saved correctly
 - [x] <strike> conflict resolution settings </strike>
 - [x] ability to delete documents
 - [x] always save before unload (or show a confirmation)
 - [x] save the document more frequently, but only when the content has actually changed
 - [x] going directly to doclist when not authenticated doesn't work
 - [x] going directly to editor page doesn't work
 - [x] add a sign out button
 - [x] <strike> access doclist directly from editor (see below comment) </strike> #129 
 - [x] better error handling (ideally some kind of dialog instead of just logging to console)
 - [x] sync documents when only the document title changes

@nt1m I have completed a rough prototype of the dropbox integration, a working example of which can be found <a href="https://standaert.net/scratchpad">here</a>. It currently doesn't have production status, so it is limited to 100 users, but there are probably a lot of bugs anyway. Add to this if you spot any issues!

I'll try and clean up the code for this and add it to the github repository in a couple of days.

**Comment by nt1m** [comment]
Nice ! One suggestion though, it'd be nice if access to the doclist was quick. Maybe there could be a sidemenu in the editor itself to quickly switch docs. Or maybe the menu button in the editor can be replaced with a back button that points to the doclist.
Also, it'd be nice to get a loading throbber in the doclist. It took a few seconds before my doc showed up. I didn't push my testing too far yet (I don't use my laptop for productivity reasons), but I will once I'll get more time, I've only tested with my iPad.

PS : your website captcha is very annoying, it keeps prompting me multiple times (each time the url changes)

**Comment by nt1m** [comment]
One other thing, it'd be nice to get an icon for each list item, and possibly a grid view

**Comment by PalmerAL** [comment]
@nt1m will try to implement those suggestions next weekend. I don't have a captcha - can you post a screenshot? Dropbox has one, but you should only have to sign in once.

**Comment by nt1m** [comment]
The captcha seems generated by your server. More precisely CloudFlare.
![image](https://cloud.githubusercontent.com/assets/1795135/6428766/876dfd00-bfad-11e4-8b49-9d00f846f9bc.jpg)
![image](https://cloud.githubusercontent.com/assets/1795135/6428768/89b62b1e-bfad-11e4-8faf-d59bb0fad09b.jpg)

**Comment by PalmerAL** [comment]
This should work now. Sorry about that!

**Comment by nt1m** [comment]
Also, instead of showing twice the title, you could show the title, then the first words in the doc as secondary text.

**Comment by nt1m** [comment]
I would also add a doc icon in front of each document in the doclist (icon-drive-document).

**Comment by PalmerAL** [comment]
Done. The first word generation needs a little more work, but it mostly works. (existing documents will be labeled as "null" until you edit them, but this shouldn't be an issue in the future)

**Comment by nt1m** [comment]
Nice ! Although, the fact that's the list text isn't aligned with the header text kinda bugs me, you could either add a doc icon for each list item, or you could add more left padding

**Comment by PalmerAL** [comment]
The document icon seems kind of unneeded since it doesn't actually tell anything about the content of the document - I'll try the padding though.

**Comment by nt1m** [comment]
The doc icon would just be for decoration purpose, the google docs home screen shows a doc icon for each item. If you're afraid it'll be too repetitive, you could lower the opacity.

Also, I found another bug, if you create a doc, and write nothing in it, then go back to the doclist, the item will show null as secondary text.

**Comment by PalmerAL** [comment]
Apparently, the dropbox api doesn't like creating two new fields that are both empty strings. I switched to using a space for the abstract initially - hopefully that will work (the changes aren't copied to standaert.net yet, so that will still say null)

**Comment by nt1m** [comment]
@PalmerAL Still not fixed yet on standaert.net (in case you have copied the changes by now). Anyways, it's not very obvious that the menu button in the editor takes you back to the list. I think a back button makes more sense in this case.

**Comment by nt1m** [comment]
It'd also be nice if you could allow Ctrl+Click or middle clicking to open a doc in a new tab (from the doclist)

**Comment by PalmerAL** [comment]
@nt1m I didn't get time to copy the changes until today - it works now. Links sound much better than onclick events, but wrapping the li's in a link screws up the formatting (as it breaks most of the direct descendent rules in material.js).

**Comment by nt1m** [comment]
Just found a new bug : objects (charts, images, ...) appear in the secondary text in the doc list

**Comment by PalmerAL** [comment]
@nt1m You might need to clear you cache. As far as I can tell, objects don't show up, and I am using textContent to get the string.
