### ISSUE TITLE
Tooltip sometimes ends up transparent

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#80]
I managed to reproduce it by selecting text quickly multiple times.
![screen shot 2015-03-01 at 17 48 55](https://cloud.githubusercontent.com/assets/1795135/6431756/52517adc-c03b-11e4-846a-280741dfde82.png)

**Comment by PalmerAL** [comment]
This is going to be hard to fix. I've only been able to reproduce this once, and there doesn't seem to be any pattern to it. Even if I select text extremely fast, it usually doesn't do this.

**Comment by nt1m** [comment]
@PalmerAL Found the reliable way to reproduce : just click the link icon in the tooltip
