### ISSUE TITLE
Improve charts dialog UI

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#92]
It kinda looks unfinished to me. I might be able to provide a mockup
- [ ] If radio buttons don't fit in the dialog, the last radio label falls into the next line
- [ ] Unnecessary scrollbars appear
- [ ] "Plus" button kinda looks strange
- [ ] Text cursor shows at a wrong position if no text is entered
- [ ] Editor tooltip can popup by focusing the table
- [ ] Dialog add chart and cancel buttons should be on the right

**Comment by nt1m** [comment]
@PalmerAL What do you think ?
![charts-dialog](https://cloud.githubusercontent.com/assets/1795135/6472969/5d1d7d14-c1f6-11e4-9f4e-d70856f22777.png)

**Comment by nt1m** [comment]
If you're worried the sidebar would take too much space, you could also go with a combo box on the right side of the tabs.

**Comment by PalmerAL** [comment]
Looks great! The sidebar is fine, although I wonder how that would work on a smaller screen.

**Comment by nt1m** [comment]
@PalmerAL Thanks, this should fit perfectly on small computer screens and tablets (probably not portrait mode though). Maybe if it could collapse into a dropdown box, and the sidebar would hide..

**Comment by nt1m** [comment]
I just saw you started the work on standaert.net. Nice !
A few remarks though  : 
- There are double vertical scrollbars with windows with small height
- You could save much space by removing the spacing on the top, the left and the right, I also think it looks much better like that
- The "+" icon should be bigger (1.5em), if you want to the height to stay the same, use the rem (root em) unit. It'd also be nice if the button was "attached" to the border like in the mockup
-  The dialog buttons should be on the right (according to spec)

**Comment by PalmerAL** [comment]
Wrapping the dialog buttons in a span to float them to the right makes the events in ui.js not work. I think it can't select the dialog correctly because it is selecting the dialog relative to the button, but I don't really feel like figuring it out today.

**Comment by nt1m** [comment]
@PalmerAL In [0], instead of $(this).parent().parent(".dialog"); , it should be $(this).parent().parent().parent(".dialog");. That would require all dialog footer to have an extra level of hierarchy, but that shouldn't be a problem since all dialogs need to have their buttons aligned to the right anyway.


[0] : https://github.com/PalmerAL/scratchpad/blob/master/editor/js/ui.js
