### ISSUE TITLE
Delightful menu animation

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#94]
@PalmerAL I was just playing around with this, what do you think ?
Code :
#start-menu-container .start-button i {
	transition: all 0.3s;
}
#start-menu-container:hover .start-button i {
	transform: rotate(225deg) scale(1.15)
}

**Comment by PalmerAL** [comment]
Looks great! I would suggest adding some margin to compensate for the scale, otherwise the icon looks uncentered vertically:

#start-menu-container .start-button i {
transition: all 0.3s;
}
#start-menu-container:hover .start-button i {
transform: rotate(225deg) scale(1.15);
margin-top: -15%;
}

**Comment by nt1m** [comment]
@PalmerAL If you look closely, the icon isn't centered even not transformed. It's a bug in the framework. I should definitely fix it

**Comment by nt1m** [comment]
@PalmerAL Just pushed a fix to Material Framework, looks perfectly aligned now.
